import { AdminPremiumManager } from '@/components/admin-premium-manager';
import { AdminAnalyticsPanel } from '@/components/admin-analytics-panel';
import { createAdminClient } from '@/lib/supabase/admin';
import { courseKeyFromProduct, courseLabelFromKey } from '@/lib/access/products';
import { buildAdminPremiumMetrics } from '@/lib/admin-premium-metrics';

export const dynamic = 'force-dynamic';

type Subscription = Record<string, any>;
type KiwifyLog = Record<string, any>;
type AnalyticsEvent = Record<string, any>;

const FALLBACK_NET_TICKET = 18.31;
function relatedProfile(value: unknown) { return Array.isArray(value) ? value[0] || null : value || null; }
function asDate(value?: string | null) { if (!value) return null; const date = new Date(value); return Number.isNaN(date.getTime()) ? null : date; }
function money(value: number) { return new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(value || 0); }
function dateLabel(value?: string | null) { const date = asDate(value); return date ? new Intl.DateTimeFormat('pt-BR', { day: '2-digit', month: '2-digit', year: 'numeric' }).format(date) : 'Sem data'; }
function startOfMonth() { const date = new Date(); date.setHours(0, 0, 0, 0); date.setDate(1); return date; }
function isActive(subscription?: Subscription | null) { return ['active', 'paid', 'approved', 'trialing'].includes(String(subscription?.status || '').toLowerCase()); }
function normalizeAmount(value: unknown) { const number = Number(value); if (!Number.isFinite(number) || number <= 0) return null; return number > 100 ? number / 100 : number; }
function subscriptionAmount(subscription?: Subscription | null) { const raw = subscription?.raw_payload || {}; for (const candidate of [raw.net_amount, raw.netAmount, raw.commission_amount, raw.price, raw.amount, raw.value, raw.order?.price, raw.order?.amount, raw.subscription?.price]) { const amount = normalizeAmount(candidate); if (amount) return amount; } return isActive(subscription) ? FALLBACK_NET_TICKET : 0; }
function statusState(subscription?: Subscription | null) { const status = String(subscription?.status || 'pending').toLowerCase(); if (isActive(subscription)) return { label: 'ativo', tone: 'active', active: true, remove: false, action: 'manter acesso' }; if (['late', 'overdue', 'past_due'].includes(status)) return { label: 'atrasado', tone: 'late', active: false, remove: false, action: 'cobrar renovação' }; if (status === 'pending') return { label: 'pendente', tone: 'pending', active: false, remove: false, action: 'aguardar pagamento' }; return { label: 'inativo', tone: 'danger', active: false, remove: true, action: 'revisar acesso' }; }
function paymentMethod(subscription?: Subscription | null) { const raw = subscription?.raw_payload || {}; const method = String(raw.payment_method || raw.paymentMethod || raw.payment?.method || raw.order?.payment_method || '').toLowerCase(); if (method.includes('card') || method.includes('credit')) return 'Cartão'; if (method.includes('pix')) return 'PIX'; if (method.includes('boleto') || method.includes('billet')) return 'Boleto'; return isActive(subscription) ? 'Recorrência' : 'Pendente'; }
function countEvents(events: AnalyticsEvent[], name: string) { return events.filter((event) => event.event === name).length; }
function uniqueUsers(events: AnalyticsEvent[]) { return new Set(events.map((event) => event.profile_id || event.email).filter(Boolean)).size; }
function rate(part: number, total: number) { return total ? (part / total) * 100 : 0; }
function labelFromScreen(value?: string | null) { return String(value || 'Hub').replace('/aluno/', '').replaceAll('/', ' › ') || 'Hub'; }
function baseAnalyticsMetrics(events: AnalyticsEvent[]) { const signupsFree = countEvents(events, 'signup_free'); const premiumBlocks = countEvents(events, 'premium_block'); const checkoutOpen = countEvents(events, 'checkout_open'); const purchases = countEvents(events, 'purchase'); const feedOpen = countEvents(events, 'feed_open'); const communityOpen = countEvents(events, 'community_open'); const libraryOpen = countEvents(events, 'library_open'); const top = new Map<string, number>(); events.filter((event) => event.event === 'premium_block').forEach((event) => { const key = labelFromScreen(event.screen); top.set(key, (top.get(key) || 0) + 1); }); return { periodLabel: 'mês atual', signupsFree, activeUsers: uniqueUsers(events), feedOpen, communityOpen, libraryOpen, premiumBlocks, checkoutOpen, purchases, renewals: countEvents(events, 'renewal'), cancels: countEvents(events, 'cancel'), upgradeRate: rate(purchases, Math.max(1, signupsFree)), checkoutRate: rate(checkoutOpen, Math.max(1, premiumBlocks)), purchaseRate: rate(purchases, Math.max(1, checkoutOpen)), blockedToCheckoutRate: rate(checkoutOpen, Math.max(1, premiumBlocks)), funnel: [{ key: 'free', label: 'Cadastro free', value: signupsFree }, { key: 'feed', label: 'Entrou no Hub', value: feedOpen }, { key: 'community', label: 'Comunidade', value: communityOpen }, { key: 'library', label: 'Biblioteca', value: libraryOpen }, { key: 'block', label: 'Bloqueio VIP', value: premiumBlocks }, { key: 'checkout', label: 'Checkout', value: checkoutOpen }, { key: 'purchase', label: 'Compra', value: purchases }], topBlocked: Array.from(top.entries()).sort((a, b) => b[1] - a[1]).slice(0, 6).map(([label, value]) => ({ label, value })) }; }
async function safeQuery(query: PromiseLike<{ data: any; error: any }>) { const { data, error } = await query; return error || !Array.isArray(data) ? [] : data; }
function eventLabel(log?: KiwifyLog | null) { const event = String(log?.event_name || '').toLowerCase(); if (event.includes('approved')) return 'Compra aprovada'; if (event.includes('renew')) return 'Renovação recebida'; if (event.includes('cancel')) return 'Cancelamento recebido'; return log?.mapped_status === 'active' ? 'Acesso liberado' : 'Evento recebido'; }
function eventTone(log?: KiwifyLog | null) { const event = String(log?.event_name || '').toLowerCase(); const status = String(log?.status || '').toLowerCase(); const mapped = String(log?.mapped_status || '').toLowerCase(); if (status === 'failed') return 'danger'; if (mapped === 'active' || event.includes('approved') || event.includes('renew')) return 'active'; if (event.includes('cancel') || event.includes('refund')) return 'danger'; return 'neutral'; }

export default async function AdminPremiumPage() {
  const supabase = createAdminClient();
  const monthStart = startOfMonth().toISOString();
  const subscriptions = (await safeQuery(supabase.from('subscriptions').select('id,status,current_period_start,current_period_end,product_name,course_key,provider_customer_id,updated_at,raw_payload,profiles(id,name,email,whatsapp,created_at)').order('updated_at', { ascending: false }).limit(3000))) as Subscription[];
  const logs = (await safeQuery(supabase.from('kiwify_webhook_events').select('id,event_name,customer_email,product_name,mapped_status,status,error_message,created_at').order('created_at', { ascending: false }).limit(30))) as KiwifyLog[];
  const analytics = (await safeQuery(supabase.from('analytics_events').select('id,event,screen,product,source,email,profile_id,metadata,created_at').gte('created_at', monthStart).order('created_at', { ascending: false }).limit(5000))) as AnalyticsEvent[];
  const metrics = buildAdminPremiumMetrics(analytics, subscriptions, baseAnalyticsMetrics(analytics));
  const logsByEmail = new Map<string, KiwifyLog>();
  for (const log of logs) { const email = String(log.customer_email || '').toLowerCase(); if (email && !logsByEmail.has(email)) logsByEmail.set(email, log); }
  const rows = subscriptions.map((subscription) => { const profile = relatedProfile(subscription.profiles); const email = String(profile?.email || subscription.provider_customer_id || 'sem-email').toLowerCase(); const state = statusState(subscription); const courseKey = subscription.course_key || courseKeyFromProduct(subscription.product_name); const lastEvent = logsByEmail.get(email) || null; const updatedAt = subscription.updated_at || subscription.current_period_start || null; return { key: `${profile?.id || subscription.id || email}-${subscription.id || email}`, student: { id: profile?.id || subscription.id || email, name: profile?.name || email.split('@')[0] || 'Sem nome', email, whatsapp: profile?.whatsapp || null }, state, renewalTone: state.tone, renewalDate: subscription.current_period_end || null, renewalDateLabel: dateLabel(subscription.current_period_end), renewalLabel: subscription.current_period_end ? `renova em ${dateLabel(subscription.current_period_end)}` : 'sem data de renovação', accessReason: state.active ? 'Assinatura ou compra liberada' : 'Verificar acesso', amount: subscriptionAmount(subscription), amountLabel: money(subscriptionAmount(subscription)), method: paymentMethod(subscription), productName: subscription.product_name || 'Produto não informado', courseKey, courseLabel: courseLabelFromKey(courseKey), lastEventLabel: eventLabel(lastEvent), lastEventTone: eventTone(lastEvent), lastEventDate: lastEvent?.created_at ? dateLabel(lastEvent.created_at) : 'sem webhook recente', whatsapp: null, estimated: false, updatedAt }; });
  const removeEmails = rows.filter((row) => row.state.remove).map((row) => row.student.email).filter(Boolean).join('\n');
  const lateEmails = rows.filter((row) => row.state.tone === 'late').map((row) => row.student.email).filter(Boolean).join('\n');
  return <main className="page admin-shell premium-admin-page premium-console"><section className="premium-console-hero compact-premium-hero"><div><p className="eyebrow">Assinaturas</p><h1>Central de receita</h1><p>Dashboard executivo: receita, MRR, assinantes, funil, produtos e atividade recente.</p></div><div className="premium-console-actions"><a href="/admin">Voltar</a></div></section><AdminAnalyticsPanel metrics={metrics} /><AdminPremiumManager rows={rows} removeEmails={removeEmails} lateEmails={lateEmails} /><aside className="premium-panel premium-events-panel"><div className="section-heading compact"><div><p className="eyebrow">Kiwify</p><h2>Movimentações recentes</h2></div><span className="pill">{logs.length}</span></div><div className="premium-event-timeline">{logs.length ? logs.map((log) => <article className={`premium-timeline-item ${eventTone(log)}`} key={log.id}><span /><div><strong>{eventLabel(log)}</strong><p>{log.customer_email || 'sem email'} · {courseLabelFromKey(courseKeyFromProduct(log.product_name))}</p><small>{log.error_message || dateLabel(log.created_at)}</small></div></article>) : <p className="muted">Nenhum webhook registrado ainda.</p>}</div></aside></main>;
}
