'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import { CheckCircle2, Headphones, Mic, Music2, Pause, Play, RefreshCcw, Send, SlidersHorizontal, Square, Video } from 'lucide-react';
import { proxiedVideoUrl } from '@/lib/audio/duet-recording-utils';
import { DuetAudioEngine } from '@/lib/audio-engine/duet-audio-engine';
import { DuetPreviewEngine } from '@/lib/audio-engine/duet-preview-engine';
import { DuetRecorderEngine, type DuetRecorderEngineResult } from '@/lib/audio-engine/duet-recorder-engine';
import { DuetRendererEngine } from '@/lib/audio-engine/duet-renderer-engine';
import { attachMediaSource } from '@/lib/media/hls-client';

type Props = { lessonTitle: string; lessonSlug: string; referenceUrl?: string | null; referenceEmbedUrl?: string | null; canSendForReview?: boolean };
type Step = 'intro' | 'recording' | 'review' | 'posting' | 'posted';
type Preset = 'natural' | 'studio' | 'worship' | 'coral';

function isSafariLike() { if (typeof navigator === 'undefined') return false; const ua = navigator.userAgent; return /iPad|iPhone|iPod/.test(ua) || (/Safari/.test(ua) && !/Chrome|Chromium|Android/.test(ua)); }
function errorText(error: unknown) { return error instanceof Error ? `${error.name}: ${error.message}` : String(error || 'erro_desconhecido'); }
function sleep(ms: number) { return new Promise((resolve) => window.setTimeout(resolve, ms)); }
function waitMediaReady(media: HTMLMediaElement, timeoutMs = 12000) { return new Promise<void>((resolve, reject) => { if (media.readyState >= 2) return resolve(); let done = false; const cleanup = (fn: () => void) => { if (done) return; done = true; window.clearTimeout(timer); media.removeEventListener('loadedmetadata', ok); media.removeEventListener('loadeddata', ok); media.removeEventListener('canplay', ok); media.removeEventListener('error', fail); fn(); }; const ok = () => cleanup(resolve); const fail = () => cleanup(() => reject(new Error('media_load_failed'))); const timer = window.setTimeout(() => cleanup(() => reject(new Error('media_load_timeout'))), timeoutMs); media.addEventListener('loadedmetadata', ok, { once: true }); media.addEventListener('loadeddata', ok, { once: true }); media.addEventListener('canplay', ok, { once: true }); media.addEventListener('error', fail, { once: true }); }); }

const presets: Record<Preset, { title: string; text: string; voice: number; reference: number }> = {
  natural: { title: 'Natural', text: 'Limpo e direto.', voice: 100, reference: 70 },
  studio: { title: 'Studio', text: 'Presença e compressão.', voice: 120, reference: 65 },
  worship: { title: 'Worship', text: 'Ambiência de louvor.', voice: 110, reference: 82 },
  coral: { title: 'Coral', text: 'Espaço para segunda voz.', voice: 96, reference: 92 },
};

export function DuetRecorder({ lessonTitle, lessonSlug, referenceUrl, canSendForReview = true }: Props) {
  const referenceSource = useMemo(() => proxiedVideoUrl(referenceUrl), [referenceUrl]);
  const cameraRef = useRef<HTMLVideoElement | null>(null);
  const referenceVideoRef = useRef<HTMLVideoElement | null>(null);
  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const previewVisualRef = useRef<HTMLVideoElement | null>(null);
  const previewVoiceRef = useRef<HTMLAudioElement | null>(null);
  const previewReferenceRef = useRef<HTMLAudioElement | null>(null);
  const recorderEngineRef = useRef<DuetRecorderEngine | null>(null);
  const previewEngineRef = useRef<DuetPreviewEngine | null>(null);
  const monitorEngineRef = useRef<DuetAudioEngine | null>(null);
  const monitorMediaRef = useRef<HTMLVideoElement | null>(null);
  const monitorAttachmentRef = useRef<{ destroy: () => void } | null>(null);

  const [step, setStep] = useState<Step>('intro');
  const [error, setError] = useState('');
  const [result, setResult] = useState<DuetRecorderEngineResult | null>(null);
  const [caption, setCaption] = useState('Minha prática do dueto.');
  const [postCommunity, setPostCommunity] = useState(!canSendForReview);
  const [sendForReview, setSendForReview] = useState(canSendForReview);
  const [postedHref, setPostedHref] = useState('');
  const [status, setStatus] = useState('');
  const [postingProgress, setPostingProgress] = useState(0);
  const [voiceVolume, setVoiceVolume] = useState(110);
  const [referenceVolume, setReferenceVolume] = useState(70);
  const [referenceOffsetMs, setReferenceOffsetMsState] = useState(0);
  const [playing, setPlaying] = useState(false);
  const [preset, setPreset] = useState<Preset>('studio');

  useEffect(() => () => { try { recorderEngineRef.current?.cleanup(); } catch {} previewEngineRef.current?.close().catch(() => undefined); stopReferenceMonitor().catch(() => undefined); }, []);

  async function startReferenceMonitor() { if (!referenceSource) return; await stopReferenceMonitor(); const media = document.createElement('video'); media.preload = 'auto'; media.playsInline = true; media.volume = 0; media.muted = false; monitorMediaRef.current = media; monitorAttachmentRef.current = await attachMediaSource(media, referenceSource); await waitMediaReady(media); const engine = new DuetAudioEngine({ latencyHint: 'interactive', sampleRate: 48000 }); engine.setPreGains({ reference: 0.35, voice: 0 }); engine.setFaders({ reference: 100, voice: 0 }); engine.connectReferenceElement(media); monitorEngineRef.current = engine; await engine.resume(); media.currentTime = 0; await media.play().catch(() => undefined); }
  async function stopReferenceMonitor() { try { monitorMediaRef.current?.pause(); } catch {} try { monitorAttachmentRef.current?.destroy(); } catch {} try { monitorMediaRef.current?.removeAttribute('src'); monitorMediaRef.current?.load(); } catch {} await monitorEngineRef.current?.close().catch(() => undefined); monitorEngineRef.current = null; monitorMediaRef.current = null; monitorAttachmentRef.current = null; }

  async function startRecording() { setError(''); setStatus(''); setPostedHref(''); setResult(null); setPostingProgress(0); setPlaying(false); if (!referenceSource) return setError('Essa atividade ainda não tem vídeo de referência vinculado.'); if (!cameraRef.current || !referenceVideoRef.current || !canvasRef.current) return setError('Elementos de gravação indisponíveis.'); try { await previewEngineRef.current?.close().catch(() => undefined); previewEngineRef.current = null; const engine = new DuetRecorderEngine({ camera: cameraRef.current, referenceVideo: referenceVideoRef.current, canvas: canvasRef.current }, { referenceUrl: referenceSource }); recorderEngineRef.current = engine; await engine.prepare(); await startReferenceMonitor(); await engine.start(); setStep('recording'); setStatus('Gravando agora. Cante junto com a referência e finalize quando terminar.'); } catch (err) { await stopReferenceMonitor(); try { recorderEngineRef.current?.cleanup(); } catch {}; recorderEngineRef.current = null; setStep('intro'); setError(`Não consegui iniciar a gravação: ${errorText(err)}`); } }
  async function stopRecording() { setError(''); const engine = recorderEngineRef.current; if (!engine) return; try { const recording = await engine.stop(); recorderEngineRef.current = null; await stopReferenceMonitor(); setResult(recording); setStep('review'); setStatus('Gravação pronta. Ajuste a mixagem antes de enviar.'); } catch (err) { await stopReferenceMonitor(); setStep('intro'); setError(`Não consegui finalizar a gravação: ${errorText(err)}`); } }

  async function ensurePreviewEngine() { if (!result?.canvasBlob || !result?.voiceBlob || !referenceSource) throw new Error('preview_missing_media'); if (!previewVisualRef.current || !previewVoiceRef.current || !previewReferenceRef.current) throw new Error('preview_refs_missing'); if (previewEngineRef.current) return previewEngineRef.current; const engine = new DuetPreviewEngine({ visual: previewVisualRef.current, voice: previewVoiceRef.current, reference: previewReferenceRef.current }, { visualBlob: result.canvasBlob, voiceBlob: result.voiceBlob, referenceUrl: referenceSource, initialFaders: { voice: voiceVolume, reference: referenceVolume }, preGains: { voice: 3.2, reference: 0.08 }, referenceOffsetMs }); previewEngineRef.current = engine; await engine.prepare(); return engine; }
  async function playPreview() { setError(''); try { const engine = await ensurePreviewEngine(); engine.setReferenceOffsetMs(referenceOffsetMs); engine.setFaders({ voice: voiceVolume, reference: referenceVolume }); await engine.play(); setPlaying(true); setStatus('Ouvindo sua mixagem.'); } catch (err) { setPlaying(false); setError(`Não consegui iniciar o preview: ${errorText(err)}`); } }
  function pausePreview() { previewEngineRef.current?.pause(); setPlaying(false); }
  function setVoice(value: number) { setVoiceVolume(value); previewEngineRef.current?.setFaders({ voice: value }); }
  function setReference(value: number) { setReferenceVolume(value); previewEngineRef.current?.setFaders({ reference: value }); }
  function setReferenceOffset(value: number) { setReferenceOffsetMsState(value); previewEngineRef.current?.setReferenceOffsetMs(value); setStatus('Sincronia ajustada. Toque em ouvir mix para conferir do início.'); }
  function applyPreset(key: Preset) { setPreset(key); setVoice(presets[key].voice); setReference(presets[key].reference); }
  function autoMix() { setVoiceVolume(110); setReferenceVolume(70); previewEngineRef.current?.autoMix(); setStatus('Auto Mix aplicado.'); }
  async function reset() { pausePreview(); await previewEngineRef.current?.close().catch(() => undefined); previewEngineRef.current = null; setResult(null); setError(''); setStatus(''); setPostedHref(''); setStep('intro'); setPostingProgress(0); setPlaying(false); }

  async function createServerRenderJob() { if (!result?.canvasBlob || !result?.voiceBlob || !referenceSource) return null; const data = new FormData(); data.set('lesson_slug', lessonSlug); data.set('caption', caption || 'Minha prática do dueto.'); data.set('visibility', postCommunity ? 'community' : 'private'); data.set('review_requested', String(canSendForReview && sendForReview)); data.set('voice_volume', String(voiceVolume)); data.set('reference_volume', String(referenceVolume)); data.set('reference_offset_ms', String(referenceOffsetMs)); data.set('reference_url', referenceSource); data.set('video', new File([result.canvasBlob], `${lessonSlug}-visual.${(result.canvasBlob.type || '').includes('webm') ? 'webm' : 'mp4'}`, { type: result.canvasBlob.type || 'video/mp4' })); data.set('voice', new File([result.voiceBlob], `${lessonSlug}-voice.${(result.voiceBlob.type || '').includes('webm') ? 'webm' : 'm4a'}`, { type: result.voiceBlob.type || 'audio/mp4' })); setStatus('Preparando seu vídeo...'); setPostingProgress(22); const response = await fetch('/api/duet-render/jobs', { method: 'POST', body: data }); if (!response.ok) { const json = await response.json().catch(() => null); throw new Error(json?.detail || json?.message || 'Não consegui preparar o vídeo.'); } const json = await response.json().catch(() => null); const jobId = String(json?.job_id || ''); if (json?.status === 'completed' && json?.output_url) { setPostingProgress(88); return String(json.output_url); } if (!jobId) return null; for (let attempt = 1; attempt <= 18; attempt += 1) { setPostingProgress(Math.min(84, 28 + attempt * 3)); await sleep(3000); const statusResponse = await fetch(`/api/duet-render/status/${jobId}`, { cache: 'no-store' }); const statusJson = await statusResponse.json().catch(() => null); const job = statusJson?.job; if (job?.status === 'completed' && job.output_url) { setPostingProgress(88); return String(job.output_url); } if (job?.status === 'failed') throw new Error(job.error_message || 'Renderização no servidor falhou.'); } return null; }
  async function saveRenderedUrl(fileUrl: string) { const visibility = postCommunity ? 'community' : 'private'; const reviewRequested = canSendForReview && sendForReview; const response = await fetch('/api/submissions/duet', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ lesson_slug: lessonSlug, caption: caption || 'Minha prática do dueto.', visibility, review_requested: reviewRequested, file_url: fileUrl }) }); if (!response.ok) { const json = await response.json().catch(() => null); throw new Error(json?.detail || json?.message || 'Não consegui salvar sua publicação.'); } return response.json().catch(() => null); }
  async function buildUploadBlob() { if (!result?.canvasBlob || !result?.voiceBlob || !referenceSource) throw new Error('missing_render_media'); if (isSafariLike() && result.safePublishBlob && result.safePublishBlob.size > 1000) { setStatus('Finalizando envio...'); setPostingProgress(72); return result.safePublishBlob; } setStatus('Finalizando sua mixagem...'); setPostingProgress(56); const renderer = new DuetRendererEngine({ visualBlob: result.canvasBlob, voiceBlob: result.voiceBlob, referenceUrl: referenceSource, faders: { voice: voiceVolume, reference: referenceVolume }, referenceOffsetMs }); const rendered = await renderer.renderVideo(); if (!rendered.blob || rendered.blob.size < 1000) throw new Error(`render_empty:${rendered.blob?.size || 0}`); setPostingProgress(80); return rendered.blob; }
  async function submit() { if (!result?.canvasBlob) return setError('Grave o dueto antes de enviar.'); const visibility = postCommunity ? 'community' : 'private'; const reviewRequested = canSendForReview && sendForReview; if (!postCommunity && !reviewRequested) return setError(canSendForReview ? 'Escolha postar na comunidade, enviar para avaliação ou os dois.' : 'No modo gratuito, poste na comunidade para continuar.'); setStep('posting'); setError(''); setStatus('Enviando sua atividade...'); setPostingProgress(10); pausePreview(); try { if (isSafariLike()) { const renderedUrl = await createServerRenderJob().catch((err) => { console.warn('[duet-render] queue failed; falling back', err); return null; }); if (renderedUrl) { setStatus('Salvando publicação...'); setPostingProgress(92); const json = await saveRenderedUrl(renderedUrl); const communityPostId = String(json?.community_post_id || ''); setPostedHref(postCommunity ? `/aluno/comunidade${communityPostId ? `#post-${communityPostId}` : ''}` : ''); setPostingProgress(100); setStep('posted'); return; } } const uploadBlob = await buildUploadBlob(); const fileType = uploadBlob.type || 'video/webm'; const data = new FormData(); data.set('lesson_slug', lessonSlug); data.set('caption', caption || 'Minha prática do dueto.'); data.set('visibility', visibility); data.set('review_requested', String(reviewRequested)); data.set('voice_volume', String(voiceVolume)); data.set('reference_volume', String(referenceVolume)); data.set('voice_preset', preset); data.set('noise_reduction', 'false'); data.set('file', new File([uploadBlob], `${lessonSlug}-dueto-final.${fileType.includes('mp4') ? 'mp4' : 'webm'}`, { type: fileType })); const response = await fetch('/api/submissions/duet', { method: 'POST', body: data }); if (!response.ok) { const json = await response.json().catch(() => null); throw new Error(json?.detail || json?.message || 'Não consegui enviar sua atividade.'); } const json = await response.json().catch(() => null); const communityPostId = String(json?.community_post_id || ''); setPostedHref(postCommunity ? `/aluno/comunidade${communityPostId ? `#post-${communityPostId}` : ''}` : ''); setPostingProgress(100); setStep('posted'); } catch (err) { setError(`Não consegui enviar sua atividade: ${errorText(err)}`); setStep('review'); setPostingProgress(0); } }

  const shell: React.CSSProperties = { minHeight: '100dvh', background: 'radial-gradient(circle at 50% 0%, rgba(245,199,107,.18), transparent 34%), linear-gradient(180deg,#050506,#09090b 54%,#030304)', color: '#fff', padding: '18px 16px 34px' };
  const wrap: React.CSSProperties = { maxWidth: 920, margin: '0 auto', display: 'grid', gap: 18 };
  const glass: React.CSSProperties = { border: '1px solid rgba(255,255,255,.12)', borderRadius: 28, background: 'linear-gradient(180deg,rgba(255,255,255,.08),rgba(255,255,255,.035))', boxShadow: '0 24px 80px rgba(0,0,0,.38)', backdropFilter: 'blur(18px)' };
  const pill: React.CSSProperties = { border: 0, borderRadius: 999, padding: '14px 20px', fontWeight: 900, display: 'inline-flex', alignItems: 'center', justifyContent: 'center', gap: 9, cursor: 'pointer', fontSize: 16 };
  const mutedPill: React.CSSProperties = { ...pill, background: 'rgba(255,255,255,.12)', color: '#fff' };
  const goldPill: React.CSSProperties = { ...pill, background: 'linear-gradient(135deg,#f8d47b,#f3bd49)', color: '#17120a' };
  const cardOption = (active: boolean): React.CSSProperties => ({ border: `1px solid ${active ? 'rgba(245,199,107,.7)' : 'rgba(255,255,255,.12)'}`, borderRadius: 18, padding: 14, background: active ? 'linear-gradient(180deg,rgba(245,199,107,.16),rgba(245,199,107,.06))' : 'rgba(255,255,255,.045)', display: 'flex', gap: 12, alignItems: 'center', cursor: 'pointer' });

  return <main style={shell}><section style={wrap}>
    <header style={{ ...glass, padding: 22, display: 'grid', gap: 10, position: 'relative', overflow: 'hidden' }}><div style={{ position: 'absolute', right: 10, bottom: -32, width: 170, height: 170, borderRadius: 999, background: 'radial-gradient(circle,rgba(245,199,107,.18),transparent 68%)' }} /><div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 12, position: 'relative' }}><span style={{ color: '#f5c76b', letterSpacing: 2, fontWeight: 950, fontSize: 13 }}>DUETO PREMIUM</span><span style={{ opacity: .7, fontSize: 13 }}>{step === 'recording' ? 'Gravando agora' : step === 'review' ? 'Mixagem' : 'Treino guiado'}</span></div><h1 style={{ margin: 0, fontSize: 'clamp(34px,8vw,56px)', lineHeight: .95, letterSpacing: -1.8, position: 'relative' }}>Grave seu dueto</h1><p style={{ margin: 0, color: 'rgba(255,255,255,.68)', fontSize: 17, position: 'relative' }}>Aula: {lessonTitle}</p><div style={{ display: 'flex', gap: 10, flexWrap: 'wrap', marginTop: 8, position: 'relative' }}><span style={{ display: 'inline-flex', gap: 7, alignItems: 'center', color: '#f6d28a', fontWeight: 800, fontSize: 13 }}><Headphones size={16} /> Use fone para melhor resultado</span><span style={{ display: 'inline-flex', gap: 7, alignItems: 'center', color: 'rgba(255,255,255,.62)', fontWeight: 700, fontSize: 13 }}><Music2 size={16} /> Mixagem em tempo real</span></div></header>
    {error ? <div style={{ ...glass, padding: 16, borderColor: 'rgba(255,80,80,.45)', color: '#ffb4b4' }}>{error}</div> : null}
    {status && step !== 'posting' ? <div style={{ ...glass, padding: 16, color: '#f5c76b', whiteSpace: 'pre-wrap' }}>{status}</div> : null}
    <section style={{ ...glass, overflow: 'hidden', padding: 0 }}><div style={{ position: 'relative', aspectRatio: '16/9', background: '#000', display: 'grid', placeItems: 'center' }}><video ref={referenceVideoRef} playsInline muted style={{ display: 'none' }} /><video ref={cameraRef} playsInline muted autoPlay style={{ display: 'none' }} /><audio ref={previewVoiceRef} preload="auto" style={{ display: 'none' }} /><audio ref={previewReferenceRef} preload="auto" style={{ display: 'none' }} />{result?.canvasBlob && step !== 'recording' ? <video ref={previewVisualRef} playsInline muted style={{ width: '100%', height: '100%', objectFit: 'contain' }} onEnded={pausePreview} /> : <canvas ref={canvasRef} width={1280} height={720} style={{ width: '100%', height: '100%', objectFit: 'cover' }} />}{step === 'intro' ? <div style={{ position: 'absolute', inset: 0, display: 'grid', placeItems: 'center', textAlign: 'center', padding: 24, background: 'radial-gradient(circle,rgba(0,0,0,.18),rgba(0,0,0,.55))' }}><div style={{ display: 'grid', placeItems: 'center', gap: 12 }}><span style={{ width: 78, height: 78, borderRadius: 999, display: 'grid', placeItems: 'center', background: 'rgba(245,199,107,.16)', border: '1px solid rgba(245,199,107,.45)', color: '#f5c76b' }}><Video size={34} /></span><strong style={{ fontSize: 18 }}>Toque para iniciar câmera e referência</strong><small style={{ color: 'rgba(255,255,255,.62)' }}>A referência será ouvida durante a gravação.</small></div></div> : null}{step === 'recording' ? <div style={{ position: 'absolute', top: 14, left: 14, background: '#e11d48', borderRadius: 999, padding: '8px 13px', fontWeight: 950, boxShadow: '0 0 24px rgba(225,29,72,.5)' }}>● Gravando</div> : null}</div></section>
    <section style={{ display: 'grid', gridTemplateColumns: 'repeat(2,minmax(0,1fr))', gap: 12 }}>{step === 'intro' ? <button style={{ ...goldPill, gridColumn: '1 / -1' }} onClick={startRecording}><Mic size={20} /> Iniciar gravação</button> : null}{step === 'recording' ? <button style={{ ...pill, gridColumn: '1 / -1', background: '#e11d48', color: '#fff' }} onClick={stopRecording}><Square size={20} /> Finalizar gravação</button> : null}{step === 'review' ? <><button style={mutedPill} onClick={reset}><RefreshCcw size={19} /> Regravar</button><button style={goldPill} onClick={submit}><Send size={19} /> Continuar envio</button></> : null}</section>
    {step === 'posting' ? <section style={{ ...glass, padding: 22, display: 'grid', gap: 14 }}><strong style={{ fontSize: 22 }}>Publicando seu dueto</strong><p style={{ margin: 0, color: 'rgba(255,255,255,.62)' }}>{status || 'Preparando sua publicação...'}</p><div style={{ height: 10, borderRadius: 999, background: 'rgba(255,255,255,.10)', overflow: 'hidden' }}><div style={{ width: `${Math.max(8, postingProgress)}%`, height: '100%', borderRadius: 999, background: 'linear-gradient(90deg,#f8d47b,#f3bd49)', transition: 'width .45s ease' }} /></div><small style={{ color: 'rgba(255,255,255,.48)' }}>Mantenha esta tela aberta até concluir.</small></section> : null}
    {step === 'review' ? <section style={{ ...glass, padding: 18, display: 'grid', gap: 16 }}><div style={{ display: 'flex', justifyContent: 'space-between', gap: 12, alignItems: 'center' }}><div><h2 style={{ margin: 0, fontSize: 24 }}>Mixagem</h2><p style={{ margin: '4px 0 0', color: 'rgba(255,255,255,.62)' }}>Ajuste sua voz e a referência antes de publicar.</p></div><SlidersHorizontal color="#f5c76b" /></div><button style={{ ...cardOption(true), width: '100%', color: '#fff' }} onClick={autoMix}>✨ Melhorar automaticamente</button><label style={{ display: 'grid', gap: 8 }}><span style={{ display: 'flex', justifyContent: 'space-between', fontWeight: 800 }}><span>Minha voz</span><span>{voiceVolume}%</span></span><input type="range" min="0" max="200" value={voiceVolume} onChange={(event) => setVoice(Number(event.target.value))} /></label><label style={{ display: 'grid', gap: 8 }}><span style={{ display: 'flex', justifyContent: 'space-between', fontWeight: 800 }}><span>Referência</span><span>{referenceVolume}%</span></span><input type="range" min="0" max="200" value={referenceVolume} onChange={(event) => setReference(Number(event.target.value))} /></label><div style={{ display: 'grid', gridTemplateColumns: 'repeat(2,minmax(0,1fr))', gap: 10 }}>{(Object.keys(presets) as Preset[]).map((key) => <button key={key} type="button" onClick={() => applyPreset(key)} style={{ ...cardOption(preset === key), color: '#fff', textAlign: 'left', minHeight: 76 }}><span><strong>{presets[key].title}</strong><br/><small style={{ color: 'rgba(255,255,255,.58)' }}>{presets[key].text}</small></span></button>)}</div><details><summary style={{ cursor: 'pointer', color: '#f5c76b', fontWeight: 900 }}>Ajustar sincronia</summary><label style={{ display: 'grid', gap: 8, marginTop: 12 }}><span style={{ display: 'flex', justifyContent: 'space-between', fontWeight: 800 }}><span>Sincronia</span><span>{referenceOffsetMs > 0 ? `+${referenceOffsetMs}` : referenceOffsetMs}ms</span></span><input type="range" min="-300" max="300" step="10" value={referenceOffsetMs} onChange={(event) => setReferenceOffset(Number(event.target.value))} /></label></details><div style={{ display: 'flex', gap: 10, flexWrap: 'wrap' }}><button style={mutedPill} onClick={() => { setVoice(100); setReference(100); setReferenceOffset(0); }}>Reset</button><button style={goldPill} onClick={playing ? pausePreview : playPreview}>{playing ? <Pause size={18} /> : <Play size={18} />}{playing ? 'Pausar mix' : 'Ouvir mix'}</button></div></section> : null}
    {step === 'review' ? <section style={{ ...glass, padding: 18, display: 'grid', gap: 14 }}><h2 style={{ margin: 0, fontSize: 24 }}>Publicação</h2><div style={{ display: 'grid', gap: 10 }}><button type="button" onClick={() => setPostCommunity(!postCommunity)} style={cardOption(postCommunity)}><span style={{ width: 26, height: 26, borderRadius: 999, display: 'grid', placeItems: 'center', background: postCommunity ? '#0ea5e9' : 'rgba(255,255,255,.10)', color: '#fff', flex: '0 0 auto' }}>{postCommunity ? '✓' : ''}</span><span style={{ textAlign: 'left' }}><strong>Postar na comunidade</strong><br /><small style={{ color: 'rgba(255,255,255,.58)' }}>Compartilhe seu dueto com os alunos.</small></span></button><button type="button" disabled={!canSendForReview} onClick={() => canSendForReview && setSendForReview(!sendForReview)} style={{ ...cardOption(sendForReview && canSendForReview), opacity: canSendForReview ? 1 : .58 }}><span style={{ width: 26, height: 26, borderRadius: 999, display: 'grid', placeItems: 'center', background: sendForReview && canSendForReview ? '#0ea5e9' : 'rgba(255,255,255,.10)', color: '#fff', flex: '0 0 auto' }}>{sendForReview && canSendForReview ? '✓' : ''}</span><span style={{ textAlign: 'left' }}><strong>Enviar para avaliação</strong><br /><small style={{ color: 'rgba(255,255,255,.58)' }}>Receba orientação do professor.</small></span></button></div><textarea value={caption} onChange={(event) => setCaption(event.target.value)} placeholder="Escreva uma legenda..." style={{ width: '100%', minHeight: 108, borderRadius: 18, padding: 14, background: 'rgba(255,255,255,.08)', color: '#fff', border: '1px solid rgba(255,255,255,.12)', outline: 'none', resize: 'vertical', boxSizing: 'border-box' }} /><button onClick={submit} style={{ ...goldPill, width: '100%' }}><Send size={19} /> Publicar dueto</button></section> : null}
    {step === 'posted' ? <section style={{ ...glass, padding: 22, display: 'grid', gap: 12, placeItems: 'start' }}><CheckCircle2 color="#86efac" size={36} /><h2 style={{ margin: 0 }}>Vídeo enviado</h2><div style={{ display: 'flex', gap: 10, flexWrap: 'wrap' }}>{postedHref ? <a style={{ ...goldPill, textDecoration: 'none' }} href={postedHref}>Ver postagem</a> : null}<a style={{ ...mutedPill, textDecoration: 'none' }} href={`/aluno/aula/${lessonSlug}`}>Voltar para aula</a></div></section> : null}
  </section></main>;
}
